apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-dep
  name: nginx-dep
  namespace: nginx-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: httpd
        name: nginx   

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-svc
  namespace: nginx-ns
spec:
  type: LoadBalancer   
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
